services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/app
      - ../../../shared:/workspace/shared
    working_dir: /workspace/app
    command: sleep infinity
    ports:
      - "8081:8081"
    networks:
      - performance-cost-optimization_dev

networks:
  performance-cost-optimization_dev:
    external: true