services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/app
      - ../../../shared:/workspace/shared
    working_dir: /workspace
    command: sleep infinity
    networks:
      - distributed-order-system_dev

networks:
  distributed-order-system_dev:
    external: true
